# Generated by Django 2.1.4 on 2019-01-01 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_url', models.TextField()),
                ('clip_slug', models.TextField()),
                ('thumbnail_url', models.TextField()),
                ('download_url', models.TextField()),
                ('caption', models.TextField()),
                ('posted', models.BooleanField(default=False)),
                ('post_minute', models.IntegerField()),
                ('queued_time', models.DateField()),
                ('post_time', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100, null=True)),
                ('consumer_key', models.CharField(max_length=100, null=True)),
                ('consumer_key_secret', models.CharField(max_length=100, null=True)),
                ('access_token', models.CharField(max_length=100, null=True, unique=True)),
                ('access_token_secret', models.CharField(max_length=100, null=True)),
                ('followers', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(blank=True, max_length=100)),
                ('game', models.CharField(blank=True, max_length=100)),
                ('curator', models.CharField(blank=True, max_length=100)),
                ('created_after', models.DateField(default=datetime.datetime.now)),
                ('max_length', models.IntegerField(default=60)),
                ('min_views', models.IntegerField(default=0)),
                ('trending', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=100)),
                ('period', models.IntegerField(default=60)),
                ('max_posts', models.IntegerField(default=1)),
                ('post_count', models.IntegerField(blank=True, default=0)),
                ('last_run', models.IntegerField(default=0)),
                ('captions', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TwitchBot.SocialMediaAccount')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together={('type', 'username')},
        ),
        migrations.AddField(
            model_name='post',
            name='account',
            field=models.ForeignKey(on_delete=-1, to='TwitchBot.SocialMediaAccount'),
        ),
        migrations.AddField(
            model_name='post',
            name='bot',
            field=models.ForeignKey(on_delete=-1, to='TwitchBot.TwitchBot'),
        ),
    ]
