# Generated by Django 2.1.4 on 2019-01-01 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TwitchBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TwitchBot.SocialMediaAccount'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TwitchBot.TwitchBot'),
        ),
        migrations.AlterField(
            model_name='post',
            name='queued_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
