# Generated by Django 2.1.4 on 2019-01-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitchBot', '0003_auto_20190101_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchbot',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
