# Generated by Django 2.1.4 on 2019-01-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitchBot', '0004_auto_20190101_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchbot',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
