# Generated by Django 2.1.4 on 2019-01-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwitchBot', '0006_auto_20190102_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitchbot',
            old_name='created_after',
            new_name='start_at',
        ),
    ]
